pipeline {
    agent none
    stages {
        stage("Build")
        {
            agent {
                docker {image: 'openjdk:11'}
            }
            steps {
                sh 'mvn -B test --file pom.xml'
            }
        }
    }
}